### ISSUE TITLE
Reverse Tokenization

### ISSUE THREAD

**Issue by strangequickly** [lispercat/sailpoint-iiq-dev-accelerator#7] opened 2020-11-02 16:37 UTC
When using Get Object, _%%example%%_ tokens from the reverse.target.properties file aren't substituted into the XML.

Great plugin by the way, thank you.

**Comment by lispercat** [comment] 2020-11-02 17:02
Does it mean that when you import the file  *%%example%%* doesn't get
substituted?
Can you please fully describe the issue so I could reproduce it?

**Comment by brianlpeltier** [comment] 2020-11-02 17:07
These are in my reverse.target.properties file:

/Application[@name\='Test\ Application']/@featuresString=%%TESTAPP_FEATURESSTRING%%
/Application[@name\='Test\ Application']/Attributes/Map/entry[@key\='user']/@value=%%TESTAPP_USER%%
/Application[@name\='Test\ Application']/Attributes/Map/entry[@key\='password']/@value=%%TESTAPP_PASSWORD%%
/Application[@name\='Test\ Application']/Attributes/Map/entry[@key\='url']/@value=%%TESTAPP_URL%%

When I hit F1 and select **Get Object**, the resulting file that opens contains stuff like this:

<entry key="password" value="2:ACP:ZSQj+8Yci%rKekBHvjpL4hoqpzFEou9NxVMzBYOxbiU="/>

when it should have this

<entry key="password" value="%%TESTAPP_PASSWORD%%"/>

Eclipse works this way when pulling an XML artifact from the server.

**Comment by lispercat** [comment] 2020-11-02 17:40
I see. So far we've been only dealing with property files in the following
format:
%%TOKEN%%=value
So the "value" is at the right hand side of the expression.
I guess a quick fix for you would be to swap the the token and value in the
file.
When I have time, I'll take a look at the "reverse" assignments, wonder how
they work in the current framework.

**Comment by strangequickly** [comment] 2020-11-02 17:50
Thank you for the response.

**Comment by lispercat** [comment] 2020-11-03 01:17
I added the fix that you requested to 1.0.18, please check

**Comment by lispercat** [comment] 2020-11-03 01:25
@strangequickly  I added the fix that you requested to 1.0.18, please check

**Comment by strangequickly** [comment] 2020-11-03 14:33
Sure thing. Reverse tokenization explained here:

https://community.sailpoint.com/t5/DA/IIQDA-IdentityIQ-Deployment-Accelerator-User-s-Guide/ta-p/76698#toc-hId-1760990032

**Comment by lispercat** [comment] 2020-11-03 16:29
Thanks! I read the explanation but I think I need to have some useful case
to implement it.
I never felt the need to use the full "round trip" for an object.
In my regular use, I have my "source" files locally with the tokens and
when I import them the tokens get replaced.
The "get object" is for me to see exactly what I have on the server side
(or I can use "compare" feature to achieve a similar goal).
I can't think of a case when I'd need to reverse my tokenization, since I
already have my source file tokenized.
Anyway, if you could describe when and why you need this feature, we'll see
what we can do.

**Comment by strangequickly** [comment] 2020-11-03 16:39
Thanks for reading into it 👍 

An example of my use case is:

Step 1: Build application in IIQ in a Sandbox environment/server
Step 2: Setup target.properties and reverse.target.properties files
Step 3: Export application from Sandbox IIQ into source/build, during export reverse.target.properties tokenizes itself without need for manual manipulation directly to XML

This way developers won't run the risk of leaving sensitive tokens in source control, saves code reviewers the task of hunting down untokenized tokens etc.

**Comment by lispercat** [comment] 2020-11-03 17:07
Interesting!
A couple of questions:

   - I don't see VSCode in those steps 1,2,3. Where does it come in?
   - Once you did step #3, you ended up with a xml source file with a
   token.
      - You still need your sandbox.target.properties with that token
      replacement to satisfy the SSD build process.
      - You'll eventually still commit that file to your source control
      system.
      - So you can't keep any sensitive tokens (btw, keeping encrypted
      passwords there is not sensitive as long as you don't commit your iiq.cfg
      and iiq.dat in the source control)


My premise is that you start your code development in VSCode on your Dev
machine and import the code from your VSCode environment to your
target server.
(Sounds like with your step #1 you build your code in the server without
any IDE?)
So at all stages of your code development you always stay in your VSCode
editor which controls your code deployment.
Let me know what I am missing from your story and how do you do step #1
without any IDE?

**Comment by strangequickly** [comment] 2020-11-03 17:15
Step 1 would take place in IdentityIQ's Web Interface (hosted in a docker container for example) through the Application Definition section. 
Step 3 would take place in VSCode pulling the newly created Application XML from the (docker server) environment and making any changes before committing to source control.

This isn't too uncommon a development workflow especially for novice users who are accustomed to the IIQ UI for building applications, rules etc. I hope that clears things up!

**Comment by lispercat** [comment] 2020-11-03 17:40
I see, I am using IIQ in docker myself, but developing in IIQ Web interface
is a pain (for me at least :)) so for my brand new environment I just
register the WF for the plugin and start creating/importing new object to
the system right away.
I guess, if you have people used to developing within the IIQ Web
interface, they probably won't use VSCode anyway.
The whole purpose of VSCode was to facilitate development from scratch or
using an existing system (your step 3).
Definitely, I can put your feature request in my "nice to have features"
but this is something that I myself would probably never use :)
Thanks for a great discussion!

**Comment by strangequickly** [comment] 2020-11-03 17:53
I'll look at coding it myself.

Thanks for your time and great work on the extension 👍

**Comment by lispercat** [comment] 2020-11-03 18:56
Closing for now as it would be a low priority for the current plugin. See if this feature request will pop up again.

**Closed by lispercat** 2020-11-03 18:56 UTC
