### ISSUE TITLE
Latest version sailpoint-iiq-dev-accelerator-1.0.29 not working

### ISSUE THREAD

**Issue by martinwoit** [lispercat/sailpoint-iiq-dev-accelerator#21] opened 2022-01-06 12:41 UTC
Hi @lispercat,
the latest version is destroying the extension and the result messages are like this:

`Command 'iiq: Evaluate BeanShell Script' resulted in an error (command 'iiq-dev-accelerator.evalBS' not found)`
or
`Command 'iiq: Get Object' resulted in an error (command 'iiq-dev-accelerator.getObject' not found)`

**Comment by lispercat** [comment] 2022-01-06 19:02
Thanks, Martin, I'll check it.

**Comment by lispercat** [comment] 2022-01-06 20:03
I pushed a 1.0.30 which is essentially a rollback to 1.0.27.
The issue is that some node's module doesn't property get installed by the
plugin install system.
If you run "npm install" in the folder, it does load all the files, but the
regular vscode install doesn't for some reason.
Now that I reverted the damage, I'll investigate the issue and post a real
fix.

**Comment by lispercat** [comment] 2022-06-20 19:39
The bug was fixed in 1.0.30

**Closed by lispercat** 2022-06-20 19:39 UTC
